# Generated by Django 4.2.5 on 2023-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='country',
            name='profile_picture_title',
        ),
        migrations.RemoveField(
            model_name='role',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='role',
            name='profile_picture_title',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/defaultProfielPicture.jpg', null=True, upload_to='core/uploads/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
