# Generated by Django 4.2.5 on 2023-10-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_country_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture_title',
            field=models.CharField(blank=True, default='defaultProfielPicture.jpg', max_length=250, null=True),
        ),
    ]
