# Generated by Django 4.2.5 on 2023-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_profile_picture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/defaultProfielPicture.jpg', null=True, upload_to='static/uploads/'),
        ),
    ]
