# Generated by Django 4.2.5 on 2023-10-16 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_timesheet_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2023, 10, 23, 17, 49, 32, 351952)),
        ),
    ]
